title: sabre.io
layout: default

# This is used to generate the default title in the header, and select the
# current sidebar.
product: dav

latest_versions:
  vobject: 4.0
  dav: 3.0.4
  event: 3.0
  http: 4.1
  xml: 1.2
  uri: 1.0
