sculpin_content_types:
    clients:
        type: meta
        meta: client
        layout: client
        permalink: pretty
    plugins:
        type: meta
        meta: plugin
        layout: default
        permalink: pretty
